

export const environment = {
  production: true,
 
  apiUrl: 'http://34.70.100.59:8080/api/',
  authenticate:'auth/login',
  menutree:'menus/menu',
  companies:'companies/company',
  countery:'places/country',
  zone:'places/zone',
  region:'places/region',
  state:'places/state',
  city:'places/city',
  postcode:'places/postcode',
  locality:'places/locality',
  office:'businesses/office',
  business:'businesses/business',
  branch:'businesses/branch',
  role:'users/role',
  user:'users/user',
  awbtype :'awb/awbtype',
  awbsalesfill :'awb/awbsalesfillvalues',
  awbsales :'awb/awbsales',
  awbpurchasefill :'awb/awbpurchasefillvalues',
  awbpurchase :'awb/awbpurchase',
  awbissuefill :'awb/awbissuefillvalues',
  awbissue :'awb/awbissue',
  postcodeall:'places/postcode/all',
  bookingAwbNumber:'book/awbnumber',
  bookingOffice:'book/office',
  bookingPincode:'book/pincode',
  bookingFillvalues:'book/fillvalues',
  searchPostcode:'book/postcode',
  searchCities:'book/city',
  searchstates:'book/state',
  localitiesOnPostCodes:'book/localitiesonpostcode',
  booking:'book/booking',
  
};
